-- schema.sql
CREATE TABLE PRICES
(
    ID         INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID   INT       NOT NULL,
    PRODUCT_ID INT       NOT NULL,
    PRICE_LIST INT       NOT NULL,
    PRIORITY   TINYINT        NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    CURR       CHAR(3)        NOT NULL,
    START_DATE TIMESTAMP      NOT NULL,
    END_DATE   TIMESTAMP      NOT NULL
);
DROP INDEX IF EXISTS IX_PRICE_RANGE;
CREATE INDEX IX_PRICE_SEARCH
    ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY);

ALTER TABLE PRICES
    ADD CONSTRAINT UQ_PRICE_TARIFF
        UNIQUE (BRAND_ID, PRODUCT_ID, PRICE_LIST);