name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    env:
      SONAR_URL: https://sonarcloud.io
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # útil para blame en Sonar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build reactor (compile + test)
        run: mvn -B -fae clean verify

      # --- NUEVO: PIT en todos los módulos con código ---
      - name: PIT (mutation testing)
        run: |
          mvn -B -fae -Pmutation-testing verify \
            -DskipTests=false \
            -Dthreads=4 -DwithHistory=true

      # --- NUEVO: convertir PIT → Sonar generic issues ---
      - name: Convert PIT → Sonar generic issues
        run: scripts/pit-to-sonar-json.sh

      # (Opcional) sube los HTML de PIT como artefacto
      - name: Upload PIT HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-reports
          path: "**/target/pit-reports/**"
          if-no-files-found: ignore

      - name: SonarCloud Analysis
        if: env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event_name == 'pull_request')
        run: |
          RPT="$(pwd)/jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml"
          echo "RPT=$RPT"
          mvn -B sonar:sonar \
          -Dsonar.organization="${SONAR_ORG}" \
          -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
          -Dsonar.host.url="${SONAR_URL}" \
          -Dsonar.token="${SONAR_TOKEN}" \
          -Dsonar.coverage.jacoco.xmlReportPaths="$RPT" \
          -Dsonar.verbose=true

