name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    env:
      SONAR_URL: https://sonarcloud.io
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # útil para blame en Sonar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build reactor (compile + test)
        run: mvn -B -fae clean verify

      - name: Inspect classes & execs
        run: |
          echo "== CLASSES =="
          find . -type d -path '*/target/classes' -maxdepth 0 -print | sed 's|^|  |'
          echo "== TEST-CLASSES =="
          find . -type d -path '*/target/test-classes' -maxdepth 0 -print | sed 's|^|  |'
          echo "== JACOCO .exec FILES (size) =="
          find . -name 'jacoco*.exec' -printf '%10s  %p\n' | sort -nr | head -n 50 || true

      - name: Check JaCoCo aggregate
        run: |
          ls -lh jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml || true
          ls -lh target/site/jacoco-aggregate/jacoco.xml || true   # fallback

      - name: SonarCloud Analysis
        if: env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event_name == 'pull_request')
        run: |
          RPT="$(pwd)/jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml"
          echo "RPT=$RPT"
          mvn -B sonar:sonar \
          -Dsonar.organization="${SONAR_ORG}" \
          -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
          -Dsonar.host.url="${SONAR_URL}" \
          -Dsonar.token="${SONAR_TOKEN}" \
          -Dsonar.coverage.jacoco.xmlReportPaths="$RPT" \
          -Dsonar.verbose=true

